# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2014-2017
  project: Request Routing Service
  version: 0.5
  release: 0.5.0
  latex_documents:
  - - Index
    - routing.tex
    - Request Routing Service
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  html_theme_options:
    github_repository: xperseguers/t3ext-routing
    github_branch: master
...
